# Generated by Django 2.1.5 on 2019-05-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20190510_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brief',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Category', verbose_name='类别'),
        ),
    ]
